#!/usr/bin/env bash

set -eu

DEFAULT_JOURNAL_DIR=$HOME/journal

usage() {
    echo "Usage: $0 [+|-days | YYYY-MM-DD | MM-DD]"
}

if [[ $# -eq 0 ]]; then
    # no arguments: date = today
    YEAR=$(date +%Y)
    MONTH=$(date +%m)
    DAY=$(date +%d)
elif [[ $1 =~ ^-[h?]$ ]]; then
    # -h: Display usage message
    usage
    exit 0
elif [[ $1 =~ ^([+-][0-9]+)$ ]]; then
    # days: date = (today +|- days)
    YEAR=$(date -v"${BASH_REMATCH[1]}"d +%Y)
    MONTH=$(date -v"${BASH_REMATCH[1]}"d +%m)
    DAY=$(date -v"${BASH_REMATCH[1]}"d +%d)
elif [[ $1 =~ ^([0-9]{1,2})-([0-9]{1,2})$ ]]; then
    # MM-DD: date = (current year)-MM-DD
    YEAR=$(date +%Y)
    MONTH=$(date -v"${BASH_REMATCH[1]}"m +%m)
    DAY=$(date -v"${BASH_REMATCH[2]}"d +%d)
elif [[ $1 =~ ^([0-9]{4})-([0-9]{1,2})-([0-9]{1,2})$ ]]; then
    # YYYY-MM-DD: date = YYYY-MM-DD
    YEAR=$(date -v"${BASH_REMATCH[1]}"y +%Y)
    MONTH=$(date -v"${BASH_REMATCH[2]}"m +%m)
    DAY=$(date -v"${BASH_REMATCH[3]}"d +%d)
else
    echo "Invalid argument: $1"
    usage
    exit 1
fi

ROOT_DIR=${JOURNAL_DIR:-$DEFAULT_JOURNAL_DIR}

DIR=$ROOT_DIR/$YEAR/$MONTH

mkdir -p "$DIR"

FILE=$DIR/${YEAR}-${MONTH}-${DAY}.md


if [ ! -f "$FILE" ]; then
    echo "${YEAR}-${MONTH}-${DAY}" >> "$FILE"
    echo $'---\n\n' >> "$FILE"
fi

vi "+normal G$" "$FILE"
